In [1]:
print("Welcome Numpy-3")

Welcome Numpy-3


In [2]:
import numpy as np

In [3]:
a = np.array([4,2,65,56,0,6,9])
a

array([ 4,  2, 65, 56,  0,  6,  9])

In [4]:
np.sort(a)

array([ 0,  2,  4,  6,  9, 56, 65])

In [5]:
a

array([ 4,  2, 65, 56,  0,  6,  9])

In [6]:
a.sort() # this is ndarray.sort

In [7]:
a

array([ 0,  2,  4,  6,  9, 56, 65])

Difference b/n ndarray.sort() and np.sort(ndarray) is that inplace and permanent sorting for earlier while the latter just sorts and returns but doesn't store.

Above is the example.

In [8]:
a = np.array([4,2,65,56,0,6,9])

In [9]:
np.argsort(a)

array([4, 1, 0, 5, 6, 3, 2], dtype=int64)

In [10]:
np.max(a)

65

In [11]:
np.argmax(a)

2

In [12]:
a = np.array([4,2,65,56,0,65, 6,9]) #multiple max values

In [13]:
np.max(a)

65

In [14]:
np.argmax(a)

2

In [15]:
np.sort(a)

array([ 0,  2,  4,  6,  9, 56, 65, 65])

In [16]:
np.argsort(a)

array([4, 1, 0, 6, 7, 3, 2, 5], dtype=int64)

In [17]:
b = np.array([[23,2,54], [17,3,42], [15,5,65]])
b

array([[23,  2, 54],
       [17,  3, 42],
       [15,  5, 65]])

In [18]:
np.sum(b)

226

In [19]:
np.sort(b) # defaults to last axis or max axis, in 2-d it is axis=1

array([[ 2, 23, 54],
       [ 3, 17, 42],
       [ 5, 15, 65]])

In [20]:
np.sort(b, axis=0)

array([[15,  2, 42],
       [17,  3, 54],
       [23,  5, 65]])

In [21]:
np.argsort(b)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]], dtype=int64)

In [22]:
np.argsort(b, axis=1)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]], dtype=int64)

In [23]:
np.argsort(b, axis=0)

array([[2, 0, 1],
       [1, 1, 0],
       [0, 2, 2]], dtype=int64)

In [24]:
np.sort?

In [31]:
### This is unpacking
a,b,c = [1,2,3]

In [32]:
print(a)
print(b)
print(c)

1
2
3


In [41]:
data1=np.array([1, 2, 3])
print(data1)

[1 2 3]


In [42]:
data1.shape

(3,)

In [43]:
a,b,c = data1.T

In [44]:
print(a)
print(b)
print(c)

1
2
3


In [25]:
data=np.loadtxt('fitness.txt', dtype='str')

In [27]:
data[:5]

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66']],
      dtype='<U10')

In [28]:
data.shape

(96, 7)

In [29]:
data[0]

array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

In [30]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [38]:
date,step_count,mood,calories_burned, hours_of_sleep,bool_of_active,weight_kg = data.T

In [39]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [45]:
step_count=np.array(step_count, dtype='int')

In [64]:
hours_of_sleep = np.array(hours_of_sleep, dtype='int')

In [46]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [47]:
np.mean(step_count)

2935.9375

In [48]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [49]:
mood[mood=='100'] = 'sad'
mood[mood=='200'] = 'neutral'
mood[mood=='300'] = 'happy'

In [50]:
mood

array(['neutral', 'sad', 'sad', 'sad', 'neutral', 'sad', 'sad', 'sad',
       'sad', 'sad', 'sad', 'sad', 'happy', 'sad', 'sad', 'sad', 'sad',
       'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral',
       'happy', 'neutral', 'happy', 'happy', 'happy', 'happy', 'happy',
       'happy', 'happy', 'neutral', 'happy', 'happy', 'happy', 'happy',
       'happy', 'happy', 'happy', 'happy', 'happy', 'happy', 'neutral',
       'happy', 'happy', 'happy', 'happy', 'happy', 'happy', 'happy',
       'happy', 'happy', 'neutral', 'sad', 'happy', 'happy', 'happy',
       'happy', 'happy', 'happy', 'happy', 'sad', 'neutral', 'neutral',
       'sad', 'sad', 'neutral', 'neutral', 'happy', 'neutral', 'neutral',
       'sad', 'neutral', 'sad', 'neutral', 'neutral', 'sad', 'sad', 'sad',
       'sad', 'happy', 'neutral', 'happy', 'neutral', 'sad', 'sad', 'sad',
       'neutral', 'neutral', 'sad', 'sad', 'happy', 'neutral', 'neutral',
       'happy'], dtype='<U10')

In [70]:
bool_of_active[bool_of_active=='0']='inactive'
bool_of_active[bool_of_active=='500']='active'

In [71]:
bool_of_active

array(['inactive', 'inactive', 'inactive', 'inactive', 'active',
       'inactive', 'inactive', 'inactive', 'inactive', 'inactive',
       'inactive', 'inactive', 'active', 'inactive', 'inactive',
       'inactive', 'inactive', 'inactive', 'inactive', 'inactive',
       'inactive', 'inactive', 'inactive', 'inactive', 'inactive',
       'active', 'inactive', 'inactive', 'inactive', 'inactive', 'active',
       'inactive', 'inactive', 'inactive', 'inactive', 'inactive',
       'active', 'active', 'active', 'active', 'active', 'active',
       'active', 'active', 'active', 'inactive', 'inactive', 'inactive',
       'inactive', 'inactive', 'inactive', 'active', 'active', 'active',
       'active', 'active', 'active', 'active', 'active', 'active',
       'active', 'active', 'active', 'inactive', 'active', 'active',
       'inactive', 'active', 'active', 'active', 'active', 'active',
       'inactive', 'active', 'active', 'active', 'active', 'inactive',
       'inactive', 'inactive', 'inacti

In [53]:
np.unique(mood)

array(['happy', 'neutral', 'sad'], dtype='<U10')

In [54]:
np.unique(mood, return_counts=True)

(array(['happy', 'neutral', 'sad'], dtype='<U10'),
 array([40, 27, 29], dtype=int64))

In [55]:
np.mean(step_count)

2935.9375

In [56]:
np.max(step_count)

7422

In [57]:
np.argmax(step_count)

69

In [58]:
date[np.argmax(step_count)]

'14-12-2017'

In [59]:
data[np.argmax(step_count)]

array(['14-12-2017', '7422', 'happy', '243', '5', '500', '64'],
      dtype='<U10')

In [60]:
calories_burned[np.argmax(step_count)]

'243'

In [62]:
np.unique(mood[step_count>4000], return_counts=True)

(array(['happy', 'neutral', 'sad'], dtype='<U10'),
 array([22,  9,  7], dtype=int64))

In [65]:
np.mean(hours_of_sleep)

5.21875

In [67]:
np.unique(mood[hours_of_sleep<5.2], return_counts=True)

(array(['happy', 'neutral', 'sad'], dtype='<U10'),
 array([20, 24, 19], dtype=int64))

In [68]:
np.unique(mood[hours_of_sleep<4], return_counts=True)

(array(['happy', 'neutral', 'sad'], dtype='<U10'),
 array([1, 5, 6], dtype=int64))

In [72]:
np.unique(bool_of_active[hours_of_sleep<4], return_counts=True)

(array(['active', 'inactive'], dtype='<U10'), array([3, 9], dtype=int64))

In [73]:
np.unique(bool_of_active[hours_of_sleep>5], return_counts=True)

(array(['active', 'inactive'], dtype='<U10'), array([16, 17], dtype=int64))

In [75]:
weight_kg = np.array(weight_kg, dtype='int')

In [76]:
weight_kg

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64])