In [1]:
print('Welcome to Numpy-4')

Welcome to Numpy-4


In [2]:
import numpy as np

In [3]:
import math
a = np.arange(1,11)
func = np.vectorize(math.log)
func(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [4]:
def cube(s):
    return s**3

In [5]:
func1=np.vectorize(cube)
func1(a)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [8]:
def complicated(s):
    return np.exp(s-1)
func2 = np.vectorize(complicated)
func2(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
func1(func(a))

array([ 0.        ,  0.33302465,  1.32596896,  2.66419722,  4.16891156,
        5.75226818,  7.36831781,  8.9916656 , 10.60775168, 12.20807155])

In [11]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [13]:
b = a.reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [14]:
a[0]=100

In [15]:
print(a)
print(b)

[100   1   2   3]
[[100   1]
 [  2   3]]


In [16]:
b[0,1] = 22

In [17]:
print(b)
print(a)

[[100  22]
 [  2   3]]
[100  22   2   3]


In [19]:
c=a+1
c

array([101,  23,   3,   4])

In [20]:
c[2]=99

In [21]:
a

array([100,  22,   2,   3])

In [22]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [23]:
d = a*1
d

array([0, 1, 2, 3])

In [24]:
d[0] = 100
d

array([100,   1,   2,   3])

In [25]:
a

array([0, 1, 2, 3])

In [26]:
b=a+0
b

array([0, 1, 2, 3])

In [27]:
b[1]=100
b

array([  0, 100,   2,   3])

In [28]:
a

array([0, 1, 2, 3])

In [29]:
np.shares_memory(a,b)

False

In [30]:
a = np.arange(4)
b = a.reshape((2,2))
print(a)
print(b)

[0 1 2 3]
[[0 1]
 [2 3]]


In [31]:
np.shares_memory(a,b)

True

In [32]:
a[2]=111
print(a)
print(b)

[  0   1 111   3]
[[  0   1]
 [111   3]]


In [38]:
a=np.arange(1,13).reshape((3,4))
b=a.reshape((6,2))
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [39]:
print(a.shape)

(3, 4)


In [40]:
print(b.shape)

(6, 2)


In [41]:
print(a.ndim)
print(b.ndim)

2
2


In [42]:
np.shares_memory(a,b)

True

In [43]:
b[1,1]=99
b

array([[ 1,  2],
       [ 3, 99],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [44]:
a

array([[ 1,  2,  3, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
c=b*2

In [46]:
a

array([[ 1,  2,  3, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
b

array([[ 1,  2],
       [ 3, 99],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [48]:
c

array([[  2,   4],
       [  6, 198],
       [ 10,  12],
       [ 14,  16],
       [ 18,  20],
       [ 22,  24]])

In [49]:
d=b.reshape((4,3))

In [50]:
np.shares_memory(d,a)

True