In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
b = [i**2 for i in a]
print(b)

[1, 4, 9, 16, 25]


In [3]:
a = np.array([1,2,3,4,5])
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [4]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [5]:
print(b)

[1 2 3 4 5]


In [6]:
type(b)

numpy.ndarray

In [7]:
b.dtype

dtype('int32')

In [8]:
a = range(10000)

In [9]:
%timeit [i**2 for i in a]

4.06 ms ± 537 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
b = np.arange(10000)

In [11]:
%timeit b**2

9.2 µs ± 931 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
a = range(10)

In [13]:
print(a)

range(0, 10)


In [14]:
for i in a:
    print(i, end="  ")

0  1  2  3  4  5  6  7  8  9  

In [15]:
b = np.arange(0, 10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
a = range(1,10,2)
for i in a:
    print(i, end= " ")

1 3 5 7 9 

In [17]:
b = np.arange(1, 10, 2)
print(b)

[1 3 5 7 9]


Below one throws error, as python range doesnt support float step size

In [18]:
a = range(1,10,2.4)
for i in a:
    print(i, end= " ")

TypeError: 'float' object cannot be interpreted as an integer

In [19]:
b = np.arange(1, 10, 0.5)
print(b)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [20]:
b = np.array([1,2,3,4,5])
print(type(b))
print(b.dtype)
print(b)

<class 'numpy.ndarray'>
int32
[1 2 3 4 5]


In [21]:
b = np.array([1,2,3,4,5, 4.5])
print(type(b))
print(b.dtype)
print(b)

<class 'numpy.ndarray'>
float64
[1.  2.  3.  4.  5.  4.5]


In [22]:
b = np.array([1,2,3,4,5, "e"])
print(type(b))
print(b.dtype)
print(b)

<class 'numpy.ndarray'>
<U11
['1' '2' '3' '4' '5' 'e']


In [23]:
b = np.array([1,2,3,4,5, True])
print(type(b))
print(b.dtype)
print(b)

<class 'numpy.ndarray'>
int32
[1 2 3 4 5 1]


In [24]:
b = np.array([1,2,3,4,5,"er", True])
print(type(b))
print(b.dtype)
print(b)

<class 'numpy.ndarray'>
<U11
['1' '2' '3' '4' '5' 'er' 'True']


What is object datatype ?? and what happens if one of the element is object datatype

In [25]:
b = np.array([1,2,3,4,5])
print(b.ndim)
print(b.shape)

1
(5,)


In [26]:
np.linspace?

In [27]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [28]:
a = np.linspace(1, 10, 10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [29]:
a = np.linspace(1, 10, 20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


The above values are equally spaced values

In [30]:
a = np.linspace(1, 10, 19)
print(a)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [101]:
type(np.linspace(1,10, 19))

numpy.ndarray

2D arrays

In [31]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
a.ndim

2

In [34]:
a.shape

(3, 3)

In [35]:
b = np.array([[1,2,3],[4,5,6,7],[7,8,9]])
b

C:\Users\rama.sarath.c.vema\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


array([list([1, 2, 3]), list([4, 5, 6, 7]), list([7, 8, 9])], dtype=object)

In [36]:
b.ndim

1

In [37]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
a.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [39]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [40]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
a.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [42]:
a.reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [43]:
a.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Bothe the dimensions,rows and columns cannt be unknown

In [44]:
a.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [45]:
a.reshape(10,2)

ValueError: cannot reshape array of size 12 into shape (10,2)

In [47]:
b = np.arange(1,17)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [48]:
b.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [52]:
b = np.arange(1,13)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
c = b.reshape((3,4))
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [54]:
print(b.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
print(c.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


From above, reshape is different from Transpose. Evident that output of reshape from (3,4) to (4,3) is different from output of Transpose of (3,4).

Flatten converts everything to 1D matrix

In [57]:
c.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
a = np.arange(1,13).reshape((3,4)) # this is chaining
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Slicing

In [60]:
a = np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [61]:
a[0:5]

array([1, 2, 3, 4, 5])

In [62]:
a[5:-1]

array([ 6,  7,  8,  9, 10, 11])

In [63]:
a[5:10]

array([ 6,  7,  8,  9, 10])

In [64]:
a[-1]

12

In [65]:
a[4]

5

In [66]:
a[-4:]

array([ 9, 10, 11, 12])

In [67]:
a[-4:-1]

array([ 9, 10, 11])

In [69]:
a[-4:0] # this is interesting

array([], dtype=int32)

We can jump values also while slicing, as below

In [70]:
a[::3] #[start:end:step]

array([ 1,  4,  7, 10])

In [71]:
a[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [72]:
a[::-2]

array([12, 10,  8,  6,  4,  2])

In [74]:
a[1:8:-2]

array([], dtype=int32)

In [75]:
a[8:1:-2]

array([9, 7, 5, 3])

In [73]:
a[-2:-10:-2] #his will work until our start value is greater than stop value

array([11,  9,  7,  5])

2D slicing

In [85]:
a = np.arange(1,13).reshape((4,3))
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [86]:
# a[row][column] -> method1 and not suggested
# a[row, column] -> method2

In [87]:
a[0]

array([1, 2, 3])

In [88]:
a[0,:]

array([1, 2, 3])

In [89]:
a[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
a[1:3, :]

array([[4, 5, 6],
       [7, 8, 9]])

In [92]:
a[1:3, :2]

array([[4, 5],
       [7, 8]])

In [93]:
a[::2, ::2]

array([[1, 3],
       [7, 9]])

In [94]:
a[1::2, ::2]

array([[ 4,  6],
       [10, 12]])

For specific rown and columns, we can provide tuple.
Either rows or columns to be specific. Both specific will refer to points

In [97]:
a[[0,1,3], :]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [100]:
a[:,[0,2,1]]

array([[ 1,  3,  2],
       [ 4,  6,  5],
       [ 7,  9,  8],
       [10, 12, 11]])

In [99]:
a[[0,1,3], [1,2,0]]

array([ 2,  6, 10])