In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
b = [i**2 for i in a]
print(b)

[1, 4, 9, 16, 25]


In [3]:
a = np.array([1,2,3,4,5])
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [4]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [6]:
print(b)

[1 2 3 4 5]


In [5]:
type(b)

numpy.ndarray

In [7]:
b.dtype

dtype('int32')

In [8]:
a = range(10000)

In [9]:
%timeit [i**2 for i in a]

5.01 ms ± 744 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
b = np.arange(10000)

In [11]:
%timeit b**2

10.5 µs ± 832 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
a = range(10)

In [13]:
print(a)

range(0, 10)


In [14]:
for i in a:
    print(i, end="  ")

0  1  2  3  4  5  6  7  8  9  

In [15]:
b = np.arange(0, 10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
a = range(1,10,2)
for i in a:
    print(i, end= " ")

1 3 5 7 9 

In [19]:
b = np.arange(1, 10, 2)
print(b)

[1 3 5 7 9]


Below one throws error, as python range doesnt support float step size

In [20]:
a = range(1,10,2.4)
for i in a:
    print(i, end= " ")

TypeError: 'float' object cannot be interpreted as an integer

In [21]:
b = np.arange(1, 10, 0.5)
print(b)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [26]:
b = np.array([1,2,3,4,5])
print(type(b))
print(b.dtype)
print(b)

<class 'numpy.ndarray'>
int32
[1 2 3 4 5]


In [27]:
b = np.array([1,2,3,4,5, 4.5])
print(type(b))
print(b.dtype)
print(b)

<class 'numpy.ndarray'>
float64
[1.  2.  3.  4.  5.  4.5]


In [28]:
b = np.array([1,2,3,4,5, "e"])
print(type(b))
print(b.dtype)
print(b)

<class 'numpy.ndarray'>
<U11
['1' '2' '3' '4' '5' 'e']


In [29]:
b = np.array([1,2,3,4,5, True])
print(type(b))
print(b.dtype)
print(b)

<class 'numpy.ndarray'>
int32
[1 2 3 4 5 1]


In [30]:
b = np.array([1,2,3,4,5,"er", True])
print(type(b))
print(b.dtype)
print(b)

<class 'numpy.ndarray'>
<U11
['1' '2' '3' '4' '5' 'er' 'True']


What is object datatype ?? and what happens if one of the element is object datatype

In [33]:
b = np.array([1,2,3,4,5])
print(b.ndim)
print(b.shape)

1
(5,)


In [34]:
np.linspace?

In [35]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [36]:
a = np.linspace(1, 10, 10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [37]:
a = np.linspace(1, 10, 20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


The above values are equally spaced values

In [38]:
a = np.linspace(1, 10, 19)
print(a)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]
