In [1]:
print('Welcome to Numpy-4')

Welcome to Numpy-4


In [2]:
import numpy as np

In [3]:
import math
a = np.arange(1,11)
func = np.vectorize(math.log)
func(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [4]:
def cube(s):
    return s**3

In [5]:
func1=np.vectorize(cube)
func1(a)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [6]:
def complicated(s):
    return np.exp(s-1)
func2 = np.vectorize(complicated)
func2(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
func1(func(a))

array([ 0.        ,  0.33302465,  1.32596896,  2.66419722,  4.16891156,
        5.75226818,  7.36831781,  8.9916656 , 10.60775168, 12.20807155])

In [8]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [9]:
b = a.reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [10]:
a[0]=100

In [11]:
print(a)
print(b)

[100   1   2   3]
[[100   1]
 [  2   3]]


In [12]:
b[0,1] = 22

In [13]:
print(b)
print(a)

[[100  22]
 [  2   3]]
[100  22   2   3]


In [14]:
c=a+1
c

array([101,  23,   3,   4])

In [15]:
c[2]=99

In [16]:
a

array([100,  22,   2,   3])

In [17]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [18]:
d = a*1
d

array([0, 1, 2, 3])

In [19]:
d[0] = 100
d

array([100,   1,   2,   3])

In [20]:
a

array([0, 1, 2, 3])

In [21]:
b=a+0
b

array([0, 1, 2, 3])

In [22]:
b[1]=100
b

array([  0, 100,   2,   3])

In [23]:
a

array([0, 1, 2, 3])

In [24]:
np.shares_memory(a,b)

False

In [25]:
a = np.arange(4)
b = a.reshape((2,2))
print(a)
print(b)

[0 1 2 3]
[[0 1]
 [2 3]]


In [26]:
np.shares_memory(a,b)

True

In [27]:
a[2]=111
print(a)
print(b)

[  0   1 111   3]
[[  0   1]
 [111   3]]


In [28]:
a=np.arange(1,13).reshape((3,4))
b=a.reshape((6,2))
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [29]:
print(a.shape)

(3, 4)


In [30]:
print(b.shape)

(6, 2)


In [31]:
print(a.ndim)
print(b.ndim)

2
2


In [32]:
np.shares_memory(a,b)

True

In [33]:
b[1,1]=99
b

array([[ 1,  2],
       [ 3, 99],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [34]:
a

array([[ 1,  2,  3, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
c=b*2

In [36]:
a

array([[ 1,  2,  3, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
b

array([[ 1,  2],
       [ 3, 99],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [38]:
c

array([[  2,   4],
       [  6, 198],
       [ 10,  12],
       [ 14,  16],
       [ 18,  20],
       [ 22,  24]])

In [39]:
d=b.reshape((4,3))

In [40]:
np.shares_memory(d,a)

True

In [41]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b=a

In [43]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
c = a.copy()

In [45]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
c[0]=100
c

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [47]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a[2]=123

In [49]:
a

array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

In [50]:
c

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [51]:
b

array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

In [52]:
np.shares_memory(a, b)

True

In [53]:
np.shares_memory(c,a)

False

In [54]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
b=a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
id(a)

2204551231600

In [57]:
id(b)

2204551231600

In [58]:
c=a.reshape(2,-1)

In [59]:
id(c)

2204546164848

In [60]:
d=a.view() ##shallow copy

In [61]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a[3]=123

In [63]:
a

array([  0,   1,   2, 123,   4,   5,   6,   7,   8,   9])

In [64]:
d

array([  0,   1,   2, 123,   4,   5,   6,   7,   8,   9])

In [65]:
b

array([  0,   1,   2, 123,   4,   5,   6,   7,   8,   9])

In [66]:
c

array([[  0,   1,   2, 123,   4],
       [  5,   6,   7,   8,   9]])

In [67]:
a = np.arange(1,25).reshape((2,3,4))
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [68]:
np.sum(a, axis=0) #in depth direction

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [69]:
np.sum(a, axis=1) # in vertical direction

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [70]:
np.sum(a, axis=2) # in horizontal direction

array([[10, 26, 42],
       [58, 74, 90]])

In [71]:
a.T

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [72]:
a[0,:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
a[:,:,0]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [74]:
a[:,:,::2]

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11]],

       [[13, 15],
        [17, 19],
        [21, 23]]])

In [75]:
# splitting

In [78]:
d = np.arange(1,13)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [79]:
np.split(d,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [80]:
np.split(d,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [81]:
np.split(d,6)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

In [82]:
np.split(d,12)

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [84]:
np.split(d, [3,5,7])

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([ 8,  9, 10, 11, 12])]

In [85]:
np.split(d, [3,5,7,14])

[array([1, 2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([ 8,  9, 10, 11, 12]),
 array([], dtype=int32)]

In [86]:
np.split(d, [3,5,7,14,18])

[array([1, 2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([ 8,  9, 10, 11, 12]),
 array([], dtype=int32),
 array([], dtype=int32)]

In [87]:
np.split(d, [3,5,7,11,14,18])

[array([1, 2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([ 8,  9, 10, 11]),
 array([12]),
 array([], dtype=int32),
 array([], dtype=int32)]

In [88]:
np.split(d, [3,3,5,7,11,14,18])

[array([1, 2, 3]),
 array([], dtype=int32),
 array([4, 5]),
 array([6, 7]),
 array([ 8,  9, 10, 11]),
 array([12]),
 array([], dtype=int32),
 array([], dtype=int32)]

In [89]:
np.split(d, [12, 7, 4,0])

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])]

In [90]:
d = np.arange(1,13).reshape((3,4))
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
np.split(d, 2 ,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [92]:
np.split(d, 4 ,axis=1)

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[ 4],
        [ 8],
        [12]])]

In [93]:
np.split(d, 3 ,axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [94]:
np.split(d, [1,2] ,axis=1)

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [95]:
np.split(d, [1] ,axis=0)

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])]

In [96]:
a = np.arange(9).reshape((3,3,1))
a

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [103]:
#np.squeeze?

In [98]:
x = np.array([[[0], [1], [2]]])

In [99]:
x.shape

(1, 3, 1)

In [100]:
np.squeeze(x)

array([0, 1, 2])

In [101]:
np.squeeze(a)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
np.squeeze(a).shape

(3, 3)

In [104]:
np.squeeze(x, axis=0)

array([[0],
       [1],
       [2]])

In [106]:
#np.squeeze(x, axis=1)

In [109]:
b = np.arange(9).reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
np.expand_dims(b,axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [111]:
np.expand_dims?

In [117]:
x = np.array([5, 9])

In [118]:
y = np.expand_dims(x, axis=0)
y

array([[5, 9]])

In [119]:
b=np.arange(9).reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [120]:
np.expand_dims(b, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])